tests: Fix wrong keyword causing Mocha 3.x to fail
>> Mocha exploded!
>> Error: Test `title` should be a "string" but "undefined" was given instead.
>>   at new Test (/home/jon/contrib/code/guv/node_modules/mocha/lib/test.js:26:11)
>>   at context.it.context.specify (/home/jon/contrib/code/guv/node_modules/mocha/lib/interfaces/bdd.js:86:18)
>>   at Suite.<anonymous> (/home/jon/contrib/code/guv/spec/scale.coffee:11:5)
>>   at Object.create (/home/jon/contrib/code/guv/node_modules/mocha/lib/interfaces/common.js:114:19)
>>   at context.describe.context.context (/home/jon/contrib/code/guv/node_modules/mocha/lib/interfaces/bdd.js:44:27)
>>   at scaleTest (/home/jon/contrib/code/guv/spec/scale.coffee:9:3)